version: "3.1"

services:

  cerberus:
    build: "./cerberus"
    restart: always
    env_file:
      - ./cerberus/.env


  ghost:
    image: ghost:4
    restart: always
    depends_on:
      - db
    environment:
      url: https://blog.uiucquant.web.illinois.edu
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
    volumes:
      - ./data/ghost/:/var/lib/ghost/content

  
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./data/mysql:/var/lib/mysql
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - "./data/mongo:/data/db/"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mongoexpress:
    image: mongo-express
    restart: always
    ports:
      - 9001:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=example
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 9005:80
    volumes:
      - "./data/nextcloud:/var/www/html"
    environment:
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
  

  mariadb:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
       - "./data/mariadb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - ghost
      - adminer
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - /etc/letsencrypt/:/etc/letsencrypt/
       - /usr/share/nginx/html:/usr/share/nginx/html