version: "3.1"

services:


  ghost:
    image: ghost:4
    restart: always
    depends_on:
      - db
    environment:
      url: https://blog.uiucquant.web.illinois.edu
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
    volumes:
      - ./data/ghost/:/var/lib/ghost/content

  
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./data/mysql:/var/lib/mysql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - ghost
      - adminer
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - /etc/letsencrypt/:/etc/letsencrypt/
       - /usr/share/nginx/html:/usr/share/nginx/html